### Exercises

In [5]:
import pandas as pd
df = pd.read_csv("../data/nyc_food.csv")
type(df)

pandas.core.frame.DataFrame

#### Exercise 1

Load the `nyc_food.csv` dataset into a Pandas DataFrame called `df`.

1. Display the first 5 rows of the dataset.
2. How many rows and columns does the dataset contain?
3. What are the names of all the columns?
4. What are the data types of each column?

In [21]:
# PUT YOUR CODE HERE
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1898 entries, 0 to 1897
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               1898 non-null   int64
 1   customer_id            1898 non-null   int64
 2   restaurant_name        1898 non-null   object
 3   cuisine_type           1898 non-null   object
 4   cost_of_the_order      1898 non-null   float64
 5   day_of_the_week        1898 non-null   object
 6   rating                 1898 non-null   object
 7   food_preparation_time  1898 non-null   int64
 8   delivery_time          1898 non-null   int64
dtypes: float64(1), int64(4), object(4)
memory usage: 133.6+ KB

,order_id,customer_id,restaurant_name,cuisine_type,cost_of_the_order,day_of_the_week,rating,food_preparation_time,delivery_time
0,1477147,337525,Hangawi,Korean,30.75,Weekend,Not given,25,20
1,1477685,358141,Blue Ribbon Sushi Izakaya,Japanese,12.08,Weekend,Not given,25,23
2,1477070,66393,Cafe Habana,Mexican,12.23,Weekday,5,23,28
3,1477334,106968,Blue Ribbon Fried Chicken,American,29.20,Weekend,3,25,15
4,1478249,76942,Dirty Bird to Go,American,11.59,Weekday,4,25,24

#### Exercise 2

1. Generate a summary of the dataset’s numerical columns using a single Pandas function.
2. What are the unique values for cuisine type?

In [24]:
# PUT YOUR CODE HERE
print(df["cuisine_type"].unique())
df.describe()

['Korean' 'Japanese' 'Mexican' 'American' 'Indian' 'Italian'
 'Mediterranean' 'Chinese' 'Middle Eastern' 'Thai' 'Southern' 'French'
 'Spanish' 'Vietnamese']

,order_id,customer_id,cost_of_the_order,food_preparation_time,delivery_time
count,1.898000e+03,1898.000000,1898.000000,1898.000000,1898.000000
mean,1.477496e+06,171168.478398,16.498851,27.371970,24.161749
std,5.480497e+02,113698.139743,7.483812,4.632481,4.972637
min,1.476547e+06,1311.000000,4.470000,20.000000,15.000000
25%,1.477021e+06,77787.750000,12.080000,23.000000,20.000000
50%,1.477496e+06,128600.000000,14.140000,27.000000,25.000000
75%,1.477970e+06,270525.000000,22.297500,31.000000,28.000000
max,1.478444e+06,405334.000000,35.410000,35.000000,33.000000

#### Exercise 3

1. Select all rows where the cuisine description is `"Chinese"`.
2. From that filtered DataFrame, display only the columns for restaurant name and cost of order.
3. Further filter the results to only include restaurants with an order cost greater than 30.
4. How many rows satisfy all of these conditions?

In [73]:
# PUT YOUR CODE HERE
df2 = df.loc[df["cuisine_type"] == "Chinese",["restaurant_name","cost_of_the_order"]]
df2.loc[df["cost_of_the_order"]>30].count()

restaurant_name      13
cost_of_the_order    13
dtype: int64

#### Exercise 4

1. Select only the columns related to restaurant name, cuisine type, and rating, and store this in a new DataFrame called `df_subset`.
2. Use `.loc` to select rows from `df_subset` with index labels from 10 to 20 (inclusive) and display them.
3. Use `.iloc` to select the first 5 rows and the first 3 columns of `df_subset`.

In [146]:
# PUT YOUR CODE HERE
df_subset = df[["restaurant_name","cuisine_type","rating"]]
print(df_subset.loc[10:20])
df_subset.iloc[0:5,0:3]

                restaurant_name   cuisine_type     rating
10   Big Wong Restaurant _¤¾Ñ¼        Chinese  Not given
11       Empanada Mama (closed)        Mexican          5
12    Blue Ribbon Fried Chicken       American          5
13                        Pylos  Mediterranean          3
14       Lucky's Famous Burgers       American  Not given
15                  Shake Shack       American          5
16                Sushi of Gari       Japanese  Not given
17    Blue Ribbon Sushi Izakaya       Japanese  Not given
18               RedFarm Hudson        Chinese          4
19            Blue Ribbon Sushi       Japanese          4
20  Five Guys Burgers and Fries       American          4

             restaurant_name cuisine_type     rating
0                    Hangawi       Korean  Not given
1  Blue Ribbon Sushi Izakaya     Japanese  Not given
2                Cafe Habana      Mexican          5
3  Blue Ribbon Fried Chicken     American          3
4           Dirty Bird to Go     American          4

#### Exercise 5

1. Sort the DataFrame by the order cost column in descending order and display the top 10 rows.
2. Sort the DataFrame by cuisine type and then by delivery time.
3. Create a new column called `cost_category`:
   - Assign `"High"` if the order cost is greater than 30
   - Assign `"Medium"` if the score is in (20, 30]
   - Assign `"Low"` if the score is less than or equal to 20
5. Display the first 10 rows of the DataFrame including this new column.

In [151]:
# PUT YOUR CODE HERE
df.rename(columns={"order_cost": "cost_of_the_order"}, inplace=True)
df.sort_values(by="cost_of_the_order", ascending=False).head(10)
df.sort_values(by=["cuisine_type", "delivery_time"]).head(10)
df["cost_category"] = None
df.loc[df["cost_of_the_order"] > 30,"cost_category"] = "High"
df.loc[(df["cost_of_the_order"] <= 30) & (df["cost_of_the_order"] > 20),"cost_category"] = "Medium"
df.loc[df["cost_of_the_order"] <= 20,"cost_category"] = "Low"
df[["cost_of_the_order","cost_category","cuisine_type", "delivery_time"]].head(10)

   cost_of_the_order cost_category   cuisine_type  delivery_time
0              30.75          High         Korean             20
1              12.08           Low       Japanese             23
2              12.23           Low        Mexican             28
3              29.20        Medium       American             15
4              11.59           Low       American             24
5              25.22        Medium         Indian             24
6               6.07           Low        Italian             21
7               5.97           Low  Mediterranean             30
8              16.44           Low         Indian             26
9               7.18           Low         Indian             26

#### Exercise 6

1. Create a new column called `total_time` by adding the preparation and delivery times.
2. Remove the day of week column
5. Rename the cost column so that it is simply called `order_cost`

In [153]:
# PUT YOUR CODE HERE
df["total_time"] = df["food_preparation_time"] + df["delivery_time"]
df.drop(columns=["day_of_the_week"], inplace=True)
df.rename(columns={"cost_of_the_order": "order_cost"}, inplace=True)
df

,order_id,customer_id,restaurant_name,cuisine_type,order_cost,rating,food_preparation_time,delivery_time,cost_category,is_expensive,fast_favorite,total_time,cuisine_short
0,1477147,337525,Hangawi,Korean,30.75,Not given,25,20,High,1,0,45,KO
1,1477685,358141,Blue Ribbon Sushi Izakaya,Japanese,12.08,Not given,25,23,Low,0,1,48,JA
2,1477070,66393,Cafe Habana,Mexican,12.23,5,23,28,Low,0,0,51,MX
3,1477334,106968,Blue Ribbon Fried Chicken,American,29.20,3,25,15,Medium,0,0,40,AM
4,1478249,76942,Dirty Bird to Go,American,11.59,4,25,24,Low,0,0,49,AM
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1893,1476701,292602,Chipotle Mexican Grill $1.99 Delivery,Mexican,22.31,5,31,17,Medium,0,0,48,MX
1894,1477421,397537,The Smile,American,12.18,5,31,19,Low,0,0,50,AM
1895,1477819,35309,Blue Ribbon Sushi,Japanese,25.22,Not given,31,24,Medium,0,0,55,JA
1896,1477513,64151,Jack's Wife Freda,Mediterranean,12.18,5,23,31,Low,0,0,54,MD
1897,1478056,120353,Blue Ribbon Sushi,Japanese,19.45,Not given,28,24,Low,0,1,52,JA

#### Exercise 7

1. Use the `map` method to create a new column named `is_expensive` that is 1 if the order cost is greater than 30 and is 0 otherwise.
2. Use the `apply` method to create a new column named `fast_favorite` which is 1 if the cuisine type is `"Japanese"` and the cost is below 20 dollars and is 0 otherwise

In [155]:
# PUT YOUR CODE HERE
df["is_expensive"] = df["order_cost"].map(lambda x: 1 if x > 30 else 0)
df["fast_favorite"] = df.apply(lambda row: 1 if (row["cuisine_type"] == "Japanese") 
                               and (row["order_cost"] < 20) else 0, axis = 1)

df[["is_expensive", "fast_favorite", "order_cost"]].head()

   is_expensive  fast_favorite  order_cost
0             1              0       30.75
1             0              1       12.08
2             0              0       12.23
3             0              0       29.20
4             0              0       11.59

#### Exercise 8

1. Use the `map` method to create a column named `cuisine_short` that implements the following mapping:
   - Korean: KO
   - Japanese: JA
   - Mexican: MX
   - American: AM
   - Indian: IN
   - Italian: IT
   - Mediterranean: MD
   - Chinese: CH
   - Middle Eastern: ME
   - Thai: TH
   - Southern: SO
   - French: FR
   - Spanish: SP
   - Vietnamese: VT

In [113]:
# PUT YOUR CODE HERE
cuisine_map = {
    "Korean": "KO",
    "Japanese": "JA",
    "Mexican": "MX",
    "American": "AM",
    "Indian": "IN",
    "Italian": "IT",
    "Mediterranean": "MD",
    "Chinese": "CH",
    "Middle Eastern": "ME",
    "Thai": "TH",
    "Southern": "SO",
    "French": "FR",
    "Spanish": "SP",
    "Vietnamese": "VT"
}

df["cuisine_short"] = df["cuisine_type"].map(cuisine_map)
df[["cuisine_type","cuisine_short"]]

       cuisine_type cuisine_short
0            Korean            KO
1          Japanese            JA
2           Mexican            MX
3          American            AM
4          American            AM
...             ...           ...
1893        Mexican            MX
1894       American            AM
1895       Japanese            JA
1896  Mediterranean            MD
1897       Japanese            JA

[1898 rows x 2 columns]

#### Exercise 9

1. Group the data by cuisine type and calculate the average order cost for each cuisine.
2. For each cuisine type, compute both the average and maximum total time (preparation + delivery).

In [156]:
# PUT YOUR CODE HERE
df["total_time"]= df["food_preparation_time"] + df["delivery_time"]
result = df.groupby("cuisine_type").agg({
    "order_cost": "mean",
    "food_preparation_time": "mean",
    "delivery_time": "mean",
    "total_time": ["mean", "max"]
})

result

               order_cost food_preparation_time delivery_time total_time
                     mean                  mean          mean       mean max
cuisine_type
American        16.319829             27.440068     24.193493  51.633562  68
Chinese         16.305209             27.511628     23.855814  51.367442  68
French          19.793889             26.888889     25.333333  52.222222  64
Indian          16.919726             27.109589     24.082192  51.191781  65
Italian         16.418691             27.483221     24.567114  52.050336  67
Japanese        16.304532             27.510638     24.131915  51.642553  68
Korean          14.001538             25.461538     20.923077  46.384615  52
Mediterranean   15.474783             27.000000     23.586957  50.586957  64
Mexican         16.933117             26.727273     24.389610  51.116883  65
Middle Eastern  18.820612             26.673469     24.081633  50.755102  67
Southern        19.300588             27.588235     23.823529  51.411765  68
Spanish         18.994167             26.916667     23.416667  50.333333  64
Thai            19.207895             27.315789     23.157895  50.473684  61
Vietnamese      12.882857             25.714286     26.142857  51.857143  59

#### Exercise 10

1. Group the data by both `is_expensive` and the cuisine type, and calculate the total number of orders for each combination.
2. For each value of `is_expensive`, compute the average preparation time and average deliverty time.
3. Create an aggregated summary that groups by the cuisine type and that includes:
   - Mean order cost
   - Mean delivery time
   - Count of orders

In [122]:
# PUT YOUR CODE HERE
df.groupby(["is_expensive", "cuisine_type"])["order_id"].count()
df.groupby("is_expensive")[["food_preparation_time", "delivery_time"]].mean()
df.groupby("cuisine_type").agg({
    "order_cost":"mean",
    "delivery_time":"mean",
    "order_id": "count"
})

                order_cost  delivery_time  order_id
cuisine_type
American         16.319829      24.193493       584
Chinese          16.305209      23.855814       215
French           19.793889      25.333333        18
Indian           16.919726      24.082192        73
Italian          16.418691      24.567114       298
Japanese         16.304532      24.131915       470
Korean           14.001538      20.923077        13
Mediterranean    15.474783      23.586957        46
Mexican          16.933117      24.389610        77
Middle Eastern   18.820612      24.081633        49
Southern         19.300588      23.823529        17
Spanish          18.994167      23.416667        12
Thai             19.207895      23.157895        19
Vietnamese       12.882857      26.142857         7

#### Exercise 11

Using the Pandas DataFrames provided to you, complete the following:

1. Merge `df_orders` and `df_customers` on `customer_id` using an inner join.
2. How many rows are in the resulting DataFrame?
3. Perform a left join using `df_orders` as the left DataFrame. What differences do you observe compared to the inner join?

In [124]:
df_orders = pd.DataFrame({
    'order_id': [1, 2, 3, 4],
    'customer_id': [101, 102, 103, 104],
    'cost': [25, 40, 15, 30]
})

df_customers = pd.DataFrame({
    'customer_id': [101, 102, 103, 105],
    'customer_name': ['Alice', 'Bob', 'Charlie', 'Diana']
})

In [135]:
# YOUR CODE HERE
df_md = df_orders.merge(df_customers, left_on="customer_id", right_on="customer_id")
print(df_md)
df_left = df_orders.merge(df_customers, on="customer_id", how="left")
print(df_left)

   order_id  customer_id  cost customer_name
0         1          101    25         Alice
1         2          102    40           Bob
2         3          103    15       Charlie
   order_id  customer_id  cost customer_name
0         1          101    25         Alice
1         2          102    40           Bob
2         3          103    15       Charlie
3         4          104    30           NaN

#### Exercise 12

Using the Pandas DataFrames provided to you, complete the following:

1. Merge the two DataFrames where `restaurant_id` matches `rest_id`.
2. Perform an outer join and examine the resulting DataFrame.
3. Identify which rows contain missing values after the merge and explain why they appear.

In [137]:
df_restaurants = pd.DataFrame({
    'restaurant_id': [1, 2, 3],
    'restaurant_name': ['Pizza Place', 'Sushi Spot', 'Burger Joint']
})

df_reviews = pd.DataFrame({
    'rest_id': [1, 1, 2, 4],
    'rating': [4.5, 4.0, 5.0, 3.5]
})

In [145]:
# YOUR CODE HERE
df_md = df_restaurants.merge(df_reviews, left_on = "restaurant_id", right_on = "rest_id")
print(df_md)
df_out = df_restaurants.merge(df_reviews, left_on = "restaurant_id", right_on = "rest_id", how = "outer")
print(df_out)
print(df_out[df_out.isnull().any(axis=1)])
print("""For the first row, restaurant exists but review does not exist.
For the second row, restaurant does not exist but review exists.""")

   restaurant_id restaurant_name  rest_id  rating
0              1     Pizza Place        1     4.5
1              1     Pizza Place        1     4.0
2              2      Sushi Spot        2     5.0
   restaurant_id restaurant_name  rest_id  rating
0            1.0     Pizza Place      1.0     4.5
1            1.0     Pizza Place      1.0     4.0
2            2.0      Sushi Spot      2.0     5.0
3            3.0    Burger Joint      NaN     NaN
4            NaN             NaN      4.0     3.5
   restaurant_id restaurant_name  rest_id  rating
3            3.0    Burger Joint      NaN     NaN
4            NaN             NaN      4.0     3.5
For the first row, restaurant exists but review does not exist.
For the second row, restaurant does not exist but review exists.