### Quiz

#### Part 1

Read in the data found in `diamonds.csv` and then print a summary of the DataFrame that shows column names, non-null counts, and data types.

In [1]:
import pandas as pd

# PUT YOUR CODE HERE
df = pd.read_csv("../data/diamonds.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  object
 2   color    53940 non-null  object
 3   clarity  53940 non-null  object
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float64
 6   x        53940 non-null  float64
 7   y        53940 non-null  float64
 8   z        53940 non-null  float64
 9   price    53940 non-null  int64
dtypes: float64(6), int64(1), object(3)
memory usage: 4.1+ MB

#### Part 2

Select only the price and carat columns from the DataFrame.

In [8]:
# PUT YOUR CODE HERE
df[["price","carat"]]

       price  carat
0        326   0.23
1        326   0.21
2        327   0.23
3        334   0.29
4        335   0.31
...      ...    ...
53935   2757   0.72
53936   2757   0.72
53937   2757   0.70
53938   2757   0.86
53939   2757   0.75

[53940 rows x 2 columns]

#### Part 3

Create a new column called `box_volume` that is the product of dimensions `x`, `y`, and `z`. Then display the new DataFrame.

In [9]:
# PUT YOUR CODE HERE
df["box_volume"]=df["x"]+df["y"]+df["z"]
df

,carat,cut,color,clarity,depth,table,x,y,z,price,box_volume
0,0.23,Ideal,E,SI2,61.5,55.0,3.95,3.98,2.43,326,10.36
1,0.21,Premium,E,SI1,59.8,61.0,3.89,3.84,2.31,326,10.04
2,0.23,Good,E,VS1,56.9,65.0,4.05,4.07,2.31,327,10.43
3,0.29,Premium,I,VS2,62.4,58.0,4.20,4.23,2.63,334,11.06
4,0.31,Good,J,SI2,63.3,58.0,4.34,4.35,2.75,335,11.44
...,...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,5.75,5.76,3.50,2757,15.01
53936,0.72,Good,D,SI1,63.1,55.0,5.69,5.75,3.61,2757,15.05
53937,0.70,Very Good,D,SI1,62.8,60.0,5.66,5.68,3.56,2757,14.90
53938,0.86,Premium,H,SI2,61.0,58.0,6.15,6.12,3.74,2757,16.01
53939,0.75,Ideal,D,SI2,62.2,55.0,5.83,5.87,3.64,2757,15.34

#### Part 4

Use either `map` or `apply` (whichever is more appropriate) to create a new column called `good_deal` which is 1 if the cut is Ideal and the price is below 500. Then display the new DataFrame.

In [31]:
# PUT YOUR CODE HERE
df["good_deal"] = df["cut"].map(lambda x:1 if x == "Ideal" else 0)
df[["good_deal","cut","price"]]

       good_deal        cut  price
0              1      Ideal    326
1              0    Premium    326
2              0       Good    327
3              0    Premium    334
4              0       Good    335
...          ...        ...    ...
53935          1      Ideal   2757
53936          0       Good   2757
53937          0  Very Good   2757
53938          0    Premium   2757
53939          1      Ideal   2757

[53940 rows x 3 columns]

#### Part 5

Find and output the maximum carat value for each color.

In [15]:
# PUT YOUR CODE HERE
df_max = df.groupby("color")["carat"].max()
df_max

color
D    3.40
E    3.05
F    3.01
G    3.01
H    4.13
I    4.01
J    5.01
Name: carat, dtype: float64

#### Part 6

Merge the `movies` and `ratings` DataFrames so that all information about the movies in `movies` is kept even if information about their rating is not available in `ratings`. Display the merged DataFrame.

In [17]:
movies = pd.DataFrame({
    "movie_id": [10, 11, 12, 13],
    "title": ["Inception", "Titanic", "Avatar", "Jaws"]
})

ratings = pd.DataFrame({
    "movie_id": [10, 11, 14],
    "rating": [8.8, 7.8, 6.5]
})

In [18]:
# PUT YOUR CODE HERE
df_mg = movies.merge(ratings,left_on = "movie_id",right_on="movie_id",how="left")
df_mg

   movie_id      title  rating
0        10  Inception     8.8
1        11    Titanic     7.8
2        12     Avatar     NaN
3        13       Jaws     NaN