### Exercises

#### Exercise 1

Check to see if any of the players are duplicated (appear more than one time in the dataset).

In [4]:
import pandas as pd

df = pd.read_csv("../data/fifa.csv", low_memory=False)

# YOUR CODE HERE
duplicate_titles = df[df["playerUrl"].duplicated()]["playerUrl"]
df[df["playerUrl"] == duplicate_titles.iloc[0]]

,photoUrl,LongName,playerUrl,Nationality,Positions,Name,Age,↓OVA,POT,Team & Contract,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
899,https://cdn.sofifa.com/players/251/698/21_60.png,Kevin Berlaso,http://sofifa.com/player/251698/kevin-berlaso/...,Ecuador,RB,K. Berlaso,32,77,77,\n Ecuador\nFree\n\n,...,High,Medium,2 ★,78,56,69,77,72,68,12
944,https://cdn.sofifa.com/players/251/698/21_60.png,Kevin Berlaso,http://sofifa.com/player/251698/kevin-berlaso/...,Ecuador,RB,K. Berlaso,32,77,77,\n Ecuador\nFree\n\n,...,High,Medium,2 ★,78,56,69,77,72,68,12

#### Exercise 2

Inspect the dataset to see if there are any problems with missing data. If there are, determine how you would like to handle these missing values and then proceed to implement your chosen method.

In [48]:
# YOUR CODE HERE
df = df.drop(columns=["Loan Date End"])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 76 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   photoUrl          18979 non-null  object
 1   LongName          18979 non-null  object
 2   playerUrl         18979 non-null  object
 3   Nationality       18979 non-null  object
 4   Positions         18979 non-null  object
 5   Name              18979 non-null  object
 6   Age               18979 non-null  int64
 7   ↓OVA              18979 non-null  int64
 8   POT               18979 non-null  int64
 9   Team & Contract   18979 non-null  object
 10  ID                18979 non-null  int64
 11  Height            18979 non-null  object
 12  Weight            18979 non-null  float64
 13  foot              18979 non-null  object
 14  BOV               18979 non-null  int64
 15  BP                18979 non-null  object
 16  Growth            18979 non-null  int64
 17  Joined            18979 non-null  object
 18  Value             18979 non-null  float64
 19  Wage              18979 non-null  float64
 20  Release Clause    18979 non-null  object
 21  Attacking         18979 non-null  int64
 22  Crossing          18979 non-null  int64
 23  Finishing         18979 non-null  int64
 24  Heading Accuracy  18979 non-null  int64
 25  Short Passing     18979 non-null  int64
 26  Volleys           18979 non-null  int64
 27  Skill             18979 non-null  int64
 28  Dribbling         18979 non-null  int64
 29  Curve             18979 non-null  int64
 30  FK Accuracy       18979 non-null  int64
 31  Long Passing      18979 non-null  int64
 32  Ball Control      18979 non-null  int64
 33  Movement          18979 non-null  int64
 34  Acceleration      18979 non-null  int64
 35  Sprint Speed      18979 non-null  int64
 36  Agility           18979 non-null  int64
 37  Reactions         18979 non-null  int64
 38  Balance           18979 non-null  int64
 39  Power             18979 non-null  int64
 40  Shot Power        18979 non-null  int64
 41  Jumping           18979 non-null  int64
 42  Stamina           18979 non-null  int64
 43  Strength          18979 non-null  int64
 44  Long Shots        18979 non-null  int64
 45  Mentality         18979 non-null  int64
 46  Aggression        18979 non-null  int64
 47  Interceptions     18979 non-null  int64
 48  Positioning       18979 non-null  int64
 49  Vision            18979 non-null  int64
 50  Penalties         18979 non-null  int64
 51  Composure         18979 non-null  int64
 52  Defending         18979 non-null  int64
 53  Marking           18979 non-null  int64
 54  Standing Tackle   18979 non-null  int64
 55  Sliding Tackle    18979 non-null  int64
 56  Goalkeeping       18979 non-null  int64
 57  GK Diving         18979 non-null  int64
 58  GK Handling       18979 non-null  int64
 59  GK Kicking        18979 non-null  int64
 60  GK Positioning    18979 non-null  int64
 61  GK Reflexes       18979 non-null  int64
 62  Total Stats       18979 non-null  int64
 63  Base Stats        18979 non-null  int64
 64  W/F               18979 non-null  object
 65  SM                18979 non-null  object
 66  A/W               18979 non-null  object
 67  D/W               18979 non-null  object
 68  IR                18979 non-null  object
 69  PAC               18979 non-null  int64
 70  SHO               18979 non-null  int64
 71  PAS               18979 non-null  int64
 72  DRI               18979 non-null  int64
 73  DEF               18979 non-null  int64
 74  PHY               18979 non-null  int64
 75  Hits              18789 non-null  float64
dtypes: float64(4), int64(55), object(17)
memory usage: 11.0+ MB

#### Exercise 3

Use mean imputation to replace missing values in the Hits column.

In [53]:
# YOUR CODE HERE

K_TO_1000 = 1000

hits_multiplier = (
    df["Hits"].str.contains("K").map(lambda x: K_TO_1000 if x else 1)
)

df["Hits"] = (
    df["Hits"].str.replace("K", "")
    .astype("float")*hits_multiplier
)

df["Hits"] = df["Hits"].fillna(df["Hits"].mean())
df["Hits"].describe()

count    18979.000000
mean        16.982490
std         73.143499
min          1.000000
25%          2.000000
50%          4.000000
75%         10.000000
max       4500.000000
Name: Hits, dtype: float64

#### Exercise 4

Remove unwanted text from the Weight column.

In [19]:
# YOUR CODE HERE
df["Weight"] = df["Weight"].str.replace("lbs", "", regex=False).astype(int)
df["Weight"].head()

0    159
1    183
2    192
3    154
4    150
Name: Weight, dtype: int64

#### Exercise 5

Remove unwanted text from the Value and Wage columns.

In [29]:
# YOUR CODE HERE
def clean_data(col):
    col = col.str.replace("€", "", regex=False)
    col = col.str.replace("M", "e6", regex=False)
    col = col.str.replace("K", "e3", regex=False)
    return col.astype(float)
df["Value"] = clean_data(df["Value"])
df["Wage"] = clean_data(df["Wage"])
df[["Value","Wage"]].head()

        Value      Wage
0  67500000.0  560000.0
1  46000000.0  220000.0
2  75000000.0  125000.0
3  87000000.0  370000.0
4  90000000.0  270000.0

#### Exercise 6

Convert the Weight, Value, and Wage columns to the `float` data type.

In [31]:
# YOUR CODE HERE
df["Weight"] = df["Weight"].astype(float)
df["Value"] = df["Value"].astype(float)
df["Wage"] = df["Wage"].astype(float)
df[["Weight","Value","Wage"]].head()

   Weight       Value      Wage
0   159.0  67500000.0  560000.0
1   183.0  46000000.0  220000.0
2   192.0  75000000.0  125000.0
3   154.0  87000000.0  370000.0
4   150.0  90000000.0  270000.0

#### Exercise 7

Utilize method chaining to do the following in a single pass:

1. Remove unwanted characters from the Release Clause column.
2. Convert data type to `float`
3. Impute missing values using median

In [33]:
# YOUR CODE HERE
(
    df["Release Clause"]
    .str.replace("€", "")
    .str.replace("M", "e6")
    .str.replace("K", "e3")
    .astype("float")
    .pipe(lambda x: x.fillna(x.median()))
)

0        138400000.0
1         75900000.0
2        159400000.0
3        161000000.0
4        166500000.0
            ...
18974        57000.0
18975       165000.0
18976        70000.0
18977       165000.0
18978       167000.0
Name: Release Clause, Length: 18979, dtype: float64

#### Exercise 8

In the Height column, determine which observations are in centimetres and which are in inches. Save the results in another variable. Then use method chaining to do the following in a single pass:

1. Remove unwanted characters from the Height column.
2. Convert data type to `float`
3. Use the previously computed variable with the inches/centimetres indicator to convert all values to inches.

In [35]:
# YOUR CODE HERE
cm = df["Height"].str.contains("centimetres")
(
    df["Height"].str.replace("centimetres", "")
    .str.replace("inches", "")
    .astype("float")
    * cm.map(lambda x: 0.393701 if x else 1)
)

0        67.000000
1        74.015788
2        74.015788
3        71.000000
4        69.015785
           ...
18974    70.000038
18975    67.000000
18976    70.000000
18977    69.015785
18978    69.015785
Name: Height, Length: 18979, dtype: float64

#### Exercise 9

Fix the foot column so that all values are either Left or Right.

In [37]:
# YOUR CODE HERE
(
    df["foot"].str.lower()
    .replace({
        "left": "Left",
        "right": "Right",
        "L": "Left",
        "R": "Right",
        "l": "Left",
        "r": "Right"
    })
)

0         Left
1        Right
2        Right
3        Right
4        Right
         ...
18974    Right
18975    Right
18976    Right
18977    Right
18978    Right
Name: foot, Length: 18979, dtype: object

#### Exercise 10

Check the Wage column for any outliers and then output those observations marked as outliers.

In [43]:
# YOUR CODE HERE
Q1 = df["Wage"].quantile(0.25)
Q3 = df["Wage"].quantile(0.75)
IQR = Q3-Q1
df[(df["Wage"] < (Q1 - 1.5*IQR)) | (df["Wage"] > (Q3 + 1.5*IQR))].head()

,photoUrl,LongName,playerUrl,Nationality,Positions,Name,Age,↓OVA,POT,Team & Contract,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,https://cdn.sofifa.com/players/158/023/21_60.png,Lionel Messi,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,RW ST CF,L. Messi,33,93,93,\n\n\n\nFC Barcelona\n2004 ~ 2021\n\n,...,Medium,Low,5 ★,85,92,91,95,38,65,372.0
1,https://cdn.sofifa.com/players/020/801/21_60.png,C. Ronaldo dos Santos Aveiro,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,ST LW,Cristiano Ronaldo,35,92,92,\n\n\n\nJuventus\n2018 ~ 2022\n\n,...,High,Low,5 ★,89,93,81,89,35,77,344.0
2,https://cdn.sofifa.com/players/200/389/21_60.png,Jan Oblak,http://sofifa.com/player/200389/jan-oblak/210005/,Slovenia,GK,J. Oblak,27,91,93,\n\n\n\nAtlético Madrid\n2014 ~ 2023\n\n,...,Medium,Medium,3 ★,87,92,78,90,52,90,86.0
3,https://cdn.sofifa.com/players/192/985/21_60.png,Kevin De Bruyne,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,CAM CM,K. De Bruyne,29,91,91,\n\n\n\nManchester City\n2015 ~ 2023\n\n,...,High,High,4 ★,76,86,93,88,64,78,163.0
4,https://cdn.sofifa.com/players/190/871/21_60.png,Neymar da Silva Santos Jr.,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,LW CAM,Neymar Jr,28,91,91,\n\n\n\nParis Saint-Germain\n2017 ~ 2022\n\n,...,High,Medium,5 ★,91,85,86,94,36,59,273.0