Part 1 (Duplicates)

In [138]:
import pandas as pd
df = pd.read_csv("data/tacoma_houses.csv",low_memory=False)
df.duplicated().sum()

0

Explanation: The duplicated() function was used to identify duplicate rows in the dataset, and the results showed that there were no duplicate rows. Therefore, no rows were removed during the duplicate cleaning process.

In [139]:
df[df.duplicated(subset=["Latitude", "Longitude", "beds", "price"], keep=False)]
df[df.duplicated(subset=["Latitude", "Longitude", "beds", "price"], keep=False)] \
.groupby(["Latitude", "Longitude", "beds", "price"]).size() \
.sort_values(ascending=False)

Latitude   Longitude    beds    price
47.224887  -122.431656  4 Beds  $540,000       3
47.113106  -122.408828  4 Beds  $564,950       2
47.264263  -122.346022  4 Beds  $975,000       2
47.248507  -122.487954  4 Beds  $538,000       2
47.251964  -122.496966  4 Beds  $535,000       2
47.253215  -122.497653  2 Beds  $487,500       2
47.254236  -122.497260  2 Beds  $501,000       2
47.257834  -122.458513  3 Beds  $450,000       2
47.261143  -122.335718  2 Beds  $439,000       2
47.261570  -122.491097  2 Beds  $466,000       2
47.266188  -122.491473  4 Beds  $730,000       2
47.243720  -122.544548  4 Beds  $819,000       2
47.270704  -122.511396  3 Beds  $635,000       2
47.274662  -122.506139  3 Beds  $485,000       2
47.275097  -122.493267  4 Beds  $730,000       2
47.276351  -122.508174  3 Beds  $710,000       2
47.284373  -122.520744  3 Beds  $560,000       2
47.300871  -122.409941  4 Beds  $760,000       2
47.303190  -122.416335  3 Beds  $820,000       2
47.307781  -122.430267  5 Beds  $975,000       2
47.244594  -122.503212  4 Beds  $480,000       2
47.242934  -122.552146  3 Beds  $485,000       2
47.114556  -122.371835  4 Beds  $599,900       2
47.229408  -122.454394  3 Beds  $390,000       2
47.126112  -122.399228  3 Beds  $535,000       2
47.140550  -122.379266  3 Beds  $565,000       2
47.142176  -122.367091  5 Beds  $1,550,000     2
47.143569  -122.403303  4 Beds  $580,000       2
47.146704  -122.432401  3 Beds  $444,000       2
47.149961  -122.417638  4 Beds  $462,500       2
47.163103  -122.539840  4 Beds  $1,485,000     2
47.165089  -122.455173  3 Beds  $415,000       2
47.169173  -122.365438  2 Beds  $600,000       2
47.176287  -122.455665  3 Beds  $475,000       2
47.196889  -122.492578  2 Beds  $370,000       2
47.200519  -122.496094  3 Beds  $625,000       2
47.201638  -122.498614  3 Beds  $510,000       2
47.202571  -122.437108  3 Beds  $440,000       2
47.211670  -122.454259  3 Beds  $433,900       2
47.227219  -122.408185  2 Beds  $375,000       2
47.229230  -122.398158  3 Beds  $600,000       2
47.312815  -122.423992  5 Beds  $1,250,000     2
dtype: int64

Explanation: Here is the additional analysis showed repeated combinations of housing features include ("Latitude", "Longitude", "beds", "price"). However, they do not represent exact duplicate rows and were not removed during Part 1 cleaning.

Part 2 (Initial Data Cleaning Plan)
Variable 1: Longitude - Longitude represents the location of a house. Location can strongly impact a house’s price.
Variable 2: Latitude - Latitude represents the location of a house. Location can strongly impact a house’s price.
Variable 3: Price - Price is the key variable used to determine the value of a house and is the main target for analysis.
Variable 4: Beds - The number of bedrooms represents the size of the house, and larger homes with more bedrooms typically have higher market values.
Variable 5: County - The different county can lead to different houses's price
Variable 6: Bathroom - The number of bathrooms also impacts a house’s price because more bathrooms increase convenience and usability for residents.
Variable 7: House size(square footage) - The size of house affects the price of a home because larger houses are generally more expensive than smaller ones.
Variable 8: Address - Exact location of the property. Location is a major driver of price differences.
Variable 9: Year Built - It has an impact on price because newer homes frequently require less maintenance and may feature modern designs and materials.
Variable 10: HOA Fees - The payment of Homeowners Association for maintaining shared community areas and services.
Variable 11: Sewer - It influences housing prices because public sewer systems are generally more convenient and require less maintenance than septic systems.
Variable 12: Living Area - The living area is important because it defines the usable indoor space where people actually live inside the house.
Variable 13: Public Remarks - The detail descriptions of the house, includes property’s features, condition, and selling points that may influence its price
Variable 14: MLS Area - This is important because it captures neighborhood characteristics such as quality, school district, safety, and distance to amenities, all of which can influence a house’s price.
Variable 15: Lot size square feet - The total land area of a property. Larger lots can increase a house’s value due to greater outdoor space, privacy, and development potential.
Variable 16: Appliances - This includes household equipment such as refrigerators, dishwashers, ovens, and washers/dryers. That can increase the house's price because they improve convenience and reduce setup costs for buyers.
Variable 17: Parking Features - This can increase a house’s value because they provide convenient and secure parking options, such as garages, driveways, or covered parking, which are important to many buyers.
Variable 18: Site features - Property amenities, such as fencing, patios, decks, internet access, irrigation systems, or utility hookups can increase the house's price because it's convenience.
Variable 19: Cooling - This can affect a house’s price because more efficient or modern cooling systems improve comfort and reduce energy costs.
Variable 20: Heating - This can affect a house’s price because more efficient or modern heating systems improve comfort and reduce energy costs.

In [94]:
df.isna().sum().sort_values(ascending=False)

Exterior Description    4508
ListingTerms            4508
Legal Description       4508
VA loan                 4508
Disclosures             4508
                        ...
Total Bedrooms             0
City                       0
Full Baths                 0
url                        0
Longitude                  0
Length: 190, dtype: int64

In [140]:
selected_cols = [
    "Latitude",
    "Longitude",
    "price",
    "County",
    "beds",
    "Bathrooms",
    "house_size",
    "Living Area",
    "Lot Size Square Feet",
    "address",
    "MLS Area",
    "Year Built",
    "HOA Fee",
    "Appliances",
    "Sewer",
    "Cooling",
    "Heating",
    "Public Remarks",
    "Parking Features",
    "Site Features"
]

df_selected = df[selected_cols]
df_selected.head(20)

,Latitude,Longitude,price,County,beds,Bathrooms,house_size,Living Area,Lot Size Square Feet,address,MLS Area,Year Built,HOA Fee,Appliances,Sewer,Cooling,Heating,Public Remarks,Parking Features,Site Features
0,47.253662,-122.501020,"$280,000",Pierce,2 Beds,1.00,800 SQFT,NaN,"21,000 sqft","722 S Mullen\nTacoma, WA 98405",26 - Central Tacoma,1950,NaN,NaN,Sewer Connected,NaN,Baseboard,Seller is an Estate. Buyer purchased As is. Te...,Attached Garage,Fenced-Partially
1,47.135711,-122.447555,"$530,000",Pierce,3 Beds,2.50,"1,944 SQFT",NaN,"9,951 sqft","13322 9th Avenue Ct S\nTacoma, WA 98444",69 - Parkland,2018,NaN,"Dishwasher(s), Dryer(s), Disposal, Microwave(s...",Sewer Connected,NaN,"90%+ High Efficiency, Forced Air, Tankless Wat...",Don't miss this beautiful home in the Tallenti...,"Driveway, Attached Garage","Cable TV, Electric Car Charging, Fenced-Fully,..."
2,47.091209,-122.381868,"$585,950",Pierce,4 Beds,2.25,"1,916 SQFT",NaN,6007,"18201 35th Avenue Ct E\nTacoma, WA 98446",99 - Spanaway,2025,$85,"Dishwasher(s), Disposal, Dryer(s), Microwave(s...",Sewer Connected,Heat Pump,"90%+ High Efficiency, Forced Air, Heat Pump","The Preserve, nestled in the Fredrickson area ...",Attached Garage,"Cable TV, Deck, Electric Car Charging, Fenced-..."
3,47.285087,-122.369776,"$530,000",Pierce,3 Beds,2.50,"1,436 SQFT","1,436 sqft","5,750 sqft","3111 58th Avenue NE\nTacoma, WA 98422",94 - Browns Point,1989,$0,"Dishwasher(s), Disposal, Refrigerator(s), Stov...",Sewer Connected,NaN,Forced Air,Beautifully updated basement rambler with alle...,"Attached Garage, Off Street","Deck, Fenced-Fully"
4,47.286240,-122.517141,"$475,000",Pierce,3 Beds,1.00,951 SQFT,NaN,"6,444 sqft","6010 N 41st Street\nTacoma, WA 98407",25 - North Tacoma,1982,$0,"Dishwasher(s), Dryer(s), Refrigerator(s), Stov...",Sewer Connected,NaN,Baseboard,"Charming 3-bedroom, 1-bath home in a prime Nor...",Attached Garage,"Fenced-Fully, High Speed Internet"
5,47.314928,-122.430700,"$1,500,000",Pierce,3 Beds,2.50,"3,580 SQFT","3,580 sqft","35,000 sqft","8204 East Side Drive NE\nTacoma, WA 98422",94 - Browns Point,1996,$0,"Dishwasher(s), Dryer(s), Microwave(s), Refrige...",Septic Tank,Heat Pump,"90%+ High Efficiency, Forced Air, Heat Pump, S...",Unobstructed Sound and mountain views highligh...,"Driveway, Attached Garage, Off Street","Cable TV, Deck, Gas Available, High Speed Inte..."
6,47.208383,-122.412233,"$569,900",Pierce,5 Beds,3.00,"1,810 SQFT",NaN,2520,"5318 E M Street\nTacoma, WA 98404",61 - Southeast Tacoma,2024,NaN,"Dishwasher(s), Dryer(s), Disposal, Microwave(s...",Sewer Connected,"90%+ High Efficiency, Central A/C, Forced Air,...","90%+ High Efficiency, Forced Air, Heat Pump, H...",Find abundant space at an exceptional value in...,"Driveway, Attached Garage","Cable TV, Electric Car Charging, Fenced-Fully,..."
7,47.292824,-122.518687,"$925,000",Pierce,5 Beds,2.25,"2,493 SQFT",NaN,"9,240 sqft","4658 N Defiance Street\nTacoma, WA 98407",13 - North Tacoma,1921,$0,"Dishwasher(s), Refrigerator(s), Stove(s)/Range(s)",Sewer Connected,Ductless,"Ductless, Wall Unit(s)",Welcome to this North End sanctuary located wa...,"Driveway, Detached Garage, Off Street","Fenced-Fully, Outbuildings, Shop"
8,47.286981,-122.519019,"$634,000",Pierce,4 Beds,1.75,"1,530 SQFT",NaN,"7,550 sqft","6108 N 42nd Street\nTacoma, WA 98407",25 - North Tacoma,1979,NaN,"Dishwasher(s), Microwave(s), Stove(s)/Range(s)",Sewer Connected,NaN,Forced Air,Live the Dream in Tacoma’s North End! Centrall...,"Driveway, Attached Garage, Off Street","Fenced-Partially, Gas Available, Patio"
9,47.291230,-122.390962,"$809,250",Pierce,4 Beds,2.50,"2,396 SQFT","2,396 sqft","9,050 sqft","3914 fairwood Boulevard NE\nTacoma, WA 98422",94 - Browns Point,1997,$440,"Dishwasher(s), Disposal, Microwave(s), Refrige...",Sewer Connected,Forced Air,Forced Air,Stunning NE Tacoma Remodel with Views! Nestled...,Attached Garage,"Gas Available, Patio, Sprinkler System"
10,47.176924,-122.381473,"$620,000",Pierce,3 Beds,2.00,"2,074 SQFT",NaN,"20,520 sqft","3520 88th Street E\nTacoma, WA 98446",64 - Parkland/Midland,1961,$0,NaN,Septic Tank,NaN,NaN,NaN,"Attached Garage, RV Parking","Deck, Fenced-Fully, RV Parking"
11,47.211306,-122.473432,"$346,000",Pierce,2 Beds,1.00,728 SQFT,NaN,"6,000 sqft","5011 S Pine Street\nTacoma, WA 98409",49 - South Tacoma,1942,NaN,"Refrigerator, Stove/Range",Sewer Connected,NaN,Baseboard,Charming South Tacoma bungalow is now availabl...,Detached Garage,"Cable TV, Fenced-Fully, High Speed Internet, O..."
12,47.248404,-122.495429,"$480,000",Pierce,3 Beds,1.25,"1,296 SQFT",NaN,"8,125 sqft","1249 S Stevens Street\nTacoma, WA 98405",26 - Central Tacoma,1922,$0,"Dishwasher(s), Dryer(s), Refrigerator(s), Stov...",Sewer Connected,Central A/C,Forced Air,"Just minutes from 6th Ave, this charming 3 bed...","Driveway, Detached Garage, Off Street","Cable TV, Deck, Fenced-Fully, Gas Available, H..."
13,47.179085,-122.411139,"$515,900",Pierce,3 Beds,2.00,"1,157 SQFT",NaN,4700,"8604 13th Avenue Ct E\nTacoma, WA 98445",64 - Parkland/Midland,2024,$70,"Dishwasher(s), Double Oven, Disposal, Microwav...",Sewer Connected,"90%+ High Efficiency, Central A/C, Forced Air,...","90%+ High Efficiency, Forced Air, Heat Pump",The American floor plan is a spacious single-s...,"Driveway, Attached Garage","Cable TV, Electric Car Charging, Fenced-Fully,..."
14,47.131411,-122.411356,"$531,000",Pierce,5 Beds,1.75,"1,796 SQFT",NaN,"15,000 sqft","13702 13th Avenue Ct E\nTacoma, WA 98445",68 - Parkland,1960,$0,"Dishwasher(s), Microwave(s), Refrigerator(s), ...",Available,NaN,Forced Air,Discover this delightful rambler- 5 Bedroom(s)...,Detached Garage,NaN
15,47.203365,-122.412062,"$390,000",Pierce,4 Beds,1.00,"1,008 SQFT",NaN,"6,000 sqft","1226 E 59th Street\nTacoma, WA 98404",61 - Southeast Tacoma,1970,$0,"Dishwasher(s), Disposal, Microwave(s), Refrige...",Sewer Connected,NaN,Baseboard,"WOW $35, 000 PRICE REDUCTION! Discover the per...",Attached Garage,NaN
16,47.266413,-122.454952,"$1,095,000",Pierce,6 Beds,2.75,"3,895 SQFT",NaN,"9,620 sqft","518 N Tacoma Avenue\nTacoma, WA 98403",20 - North Tacoma,1930,$0,"Dishwasher(s), Disposal, Dryer(s), Microwave(s...",Sewer Connected,NaN,Radiant,Vintage Craftsmen located in the highly sought...,"Driveway, Attached Garage, Off Street","Fenced-Partially, Gas Available, Outbuildings,..."
17,47.161867,-122.426826,"$415,000",Pierce,3 Beds,1.75,"1,386 SQFT",NaN,4205,"310 105th Street E\nTacoma, WA 98445",64 - Parkland/Midland,1996,$316,"Dishwasher(s), Dryer(s), Microwave(s), Refrige...",Sewer Connected,"Central A/C, Forced Air",90%+ High Efficiency,"Well maintained 1 level living, 3bd 1.75 bath ...",Attached Garage,"Cable TV, Fenced-Fully, Gas Available, Gated E..."
18,47.263317,-122.510938,"$525,678",Pierce,3 Beds,1.50,"1,446 SQFT",NaN,"8,712 sqft","1414 N Shirley Street\nTacoma, WA 98406",24 - North Tacoma,1960,$0,NaN,Sewer Connected,NaN,Forced Air,NaN,Attached Garage,Patio
19,47.193653,-122.492637,"$325,000",Pierce,2 Beds,0.75,"1,681 SQFT","1,681 sqft","8,712 sqft","6931 S Tyler Street\nTacoma, WA 98409",45 - South Tacoma,1925,$0,"Refrigerator(s), Stove(s)/Range(s)",Sewer Connected,NaN,Wall Unit(s),Unlock the potential of this vintage Tacoma eq...,"Driveway, Detached Garage, Off Street, RV Parking","Cable TV, Fenced-Partially, Gas Available, Out..."

In [141]:
df[["Latitude",
    "Longitude",
    "price",
    "County",
    "beds",
    "Bathrooms",
    "house_size",
    "Living Area",
    "Lot Size Square Feet",
    "address",
    "MLS Area",
    "Year Built",
    "HOA Fee",
    "Appliances",
    "Sewer",
    "Cooling",
    "Heating",
    "Public Remarks",
    "Parking Features",
    "Site Features"]].isnull().sum()

Latitude                   0
Longitude                  0
price                      0
County                     0
beds                       0
Bathrooms                  1
house_size                 0
Living Area             3553
Lot Size Square Feet       3
address                    0
MLS Area                   0
Year Built                 0
HOA Fee                 1506
Appliances               342
Sewer                     36
Cooling                 2387
Heating                  151
Public Remarks           123
Parking Features          91
Site Features            489
dtype: int64

In [142]:
df["Bathrooms"] = df["Bathrooms"].fillna(df["Bathrooms"].median())
df["Bathrooms"].isnull().sum()

0

In [143]:
df["Lot Size Square Feet"] = (
    df["Lot Size Square Feet"].str.replace("sqft", "")
    .str.replace(",", "")
    .str.strip()
    .astype("float")
)
df["Lot Size Square Feet"]
df["Lot Size Square Feet"] = df["Lot Size Square Feet"].fillna(
    df["Lot Size Square Feet"].median()
)
df["Lot Size Square Feet"].isnull().sum()

0

In [144]:
df["Sewer"] = df["Sewer"].fillna(df["Sewer"].mode()[0])
df["Sewer"].isnull().sum()

0

In [145]:
df = df.drop(columns=['Living Area'])
print('Living Area' in df.columns)

False

In [146]:
df["HOA Fee"] = (
    df["HOA Fee"]
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.strip()
    .astype(float)
)
df["HOA Fee"] = df["HOA Fee"].fillna(0)
df["HOA Fee"].isnull().sum()

0

In [147]:
df["Cooling"] = df["Cooling"].fillna("None")
df["Cooling"].isnull().sum()

0

In [148]:
df["Appliances"] = df["Appliances"].fillna("None")
df["Appliances"].isnull().sum()

0

In [149]:
df["Heating"] = df["Heating"].fillna("Not Listed")
df["Heating"].isnull().sum()

0

In [150]:
df["Public Remarks"] = df["Public Remarks"].fillna("Not Listed")
df["Public Remarks"].isnull().sum()

0

In [151]:
df = df.dropna(subset=["Parking Features"])
df["Parking Features"].isnull().sum()

0

In [152]:
df["Site Features"] = df["Site Features"].fillna("Not Listed")
df["Site Features"].isnull().sum()

0

In [153]:
df["house_size"] = (
    df["house_size"].str.replace(" SQFT", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.strip()
    .astype("float")
)
df["house_size"]

0        800.0
1       1944.0
2       1916.0
3       1436.0
4        951.0
         ...
4504    1536.0
4505    2134.0
4506    1902.0
4507    1800.0
4508    3601.0
Name: house_size, Length: 4418, dtype: float64

In [154]:
df["beds"] = (
    df['beds'].str.replace(" Beds", "", regex=False)
    .str.replace(" Bed", "", regex=False)
    .str.strip()
    .astype("int")
)
df["beds"]

0       2
1       3
2       4
3       3
4       3
       ..
4504    3
4505    3
4506    4
4507    4
4508    4
Name: beds, Length: 4418, dtype: int64

In [155]:
df["price"] = (
    df["price"].str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.strip()
    .astype("float")
)
df["price"]

0        280000.0
1        530000.0
2        585950.0
3        530000.0
4        475000.0
          ...
4504     530000.0
4505     592000.0
4506     520000.0
4507     332500.0
4508    1950000.0
Name: price, Length: 4418, dtype: float64

In [156]:
variables = [
    'Latitude', 'Longitude', 'price', 'County', 'beds',
    'Bathrooms', 'house_size', 'Lot Size Square Feet',
    'address', 'MLS Area', 'Year Built', 'HOA Fee',
    'Appliances', 'Sewer', 'Cooling', 'Heating',
    'Public Remarks', 'Parking Features', 'Site Features'
]

print(df[variables].dtypes)

Latitude                float64
Longitude               float64
price                   float64
County                   object
beds                      int64
Bathrooms               float64
house_size              float64
Lot Size Square Feet    float64
address                  object
MLS Area                 object
Year Built                int64
HOA Fee                 float64
Appliances               object
Sewer                    object
Cooling                  object
Heating                  object
Public Remarks           object
Parking Features         object
Site Features            object
dtype: object

In [159]:

df["Sewer"] = df["Sewer"].str.lower().str.strip()
sewer_map = {
    "sewer connected": "Sewer Connected",
    "publicsewer": "Sewer Connected",
    "step sewer": "Sewer Connected",
    "available": "Available",
    "septic tank": "Septic Tank"
}

df["Sewer"] = df["Sewer"].replace(sewer_map)
df.loc[df["Sewer"].str.contains("sewer connected", na=False), "Sewer"] = "Sewer Connected"
df.loc[df["Sewer"].str.contains("septic tank", na=False), "Sewer"] = "Septic Tank"
df.loc[df["Sewer"].str.contains("available", na=False), "Sewer"] = "Available"
df["Sewer"].str.lower().value_counts()

Sewer
sewer connected    3919
septic tank         409
available            90
Name: count, dtype: int64

In [165]:
df["Cooling"] = df["Cooling"].str.lower().str.strip()

df.loc[df["Cooling"].str.contains("central a/c|central ac", na=False), "Cooling"] = "Central AC"
df.loc[df["Cooling"].str.contains("heat pump", na=False), "Cooling"] = "Heat Pump"
df.loc[df["Cooling"].str.contains("forced air", na=False), "Cooling"] = "Forced Air"
df.loc[df["Cooling"].str.contains("ductless|mini split", na=False), "Cooling"] = "Ductless Mini Split"
df.loc[df["Cooling"].str.fullmatch("none", na=False), "Cooling"] = "None"

main_categories = [
    "Central AC",
    "Heat Pump",
    "Forced Air",
    "Ductless Mini Split",
    "None"
]

def map_cooling(x):
    if x in main_categories:
        return x
    return "Other"

df["Cooling"] = df["Cooling"].apply(map_cooling)
df["Cooling"].str.lower().value_counts()

Cooling
none                   2319
central ac              729
heat pump               497
ductless mini split     382
forced air              323
other                   168
Name: count, dtype: int64

In [166]:
df["Heating"] = df["Heating"].str.lower().str.strip()

df.loc[df["Heating"].str.contains("forced air", na=False), "Heating"] = "Forced Air"
df.loc[df["Heating"].str.contains("baseboard", na=False), "Heating"] = "Baseboard"
df.loc[df["Heating"].str.contains("wall unit", na=False), "Heating"] = "Wall Unit"
df.loc[df["Heating"].str.contains("heat pump", na=False), "Heating"] = "Heat Pump"
df.loc[df["Heating"].str.contains("ductless|mini split|minisplit", na=False), "Heating"] = "Ductless Mini Split"

main_categories = [
    "Forced Air",
    "Baseboard",
    "Wall Unit",
    "Heat Pump",
    "Ductless Mini Split"
]

def map_heating(x):
    if x in main_categories:
        return x
    return "Other"

df["Heating"] = df["Heating"].apply(map_heating)

df["Heating"].value_counts()
df["Heating"].str.lower().value_counts()

Heating
forced air             2864
baseboard               554
wall unit               450
other                   258
heat pump               170
ductless mini split     122
Name: count, dtype: int64

In [170]:
df["Parking Features"] = df["Parking Features"].str.lower().str.strip()

df.loc[df["Parking Features"].str.contains("attached garage", na=False), "Parking Features"] = "Attached Garage"
df.loc[df["Parking Features"].str.contains("detached garage", na=False), "Parking Features"] = "Detached Garage"
df.loc[df["Parking Features"].str.contains("driveway", na=False), "Parking Features"] = "Attached Garage"
df.loc[df["Parking Features"].str.contains("off street", na=False), "Parking Features"] = "Off Street Parking"

main_categories = [
    "Attached Garage",
    "Detached Garage",
    "Off Street Parking",
]

df["Parking Features"] = df["Parking Features"].apply(
    lambda x: x if x in main_categories else "Other"
)
df["Parking Features"].str.lower().value_counts()

Parking Features
attached garage       2712
detached garage       1269
off street parking     290
other                  147
Name: count, dtype: int64

In [183]:
df_clean = df.drop(columns=[
    "address",
    "Public Remarks",
    "Site Features",
    "Appliances"
], inplace=True)

Those variables were removed because they have lots of many categories and too messy text columns for clean encoding.

Part 3 (Implement Data Cleaning Plan)

In [185]:
selected_cols = [
    "Latitude",
    "Longitude",
    "price",
    "County",
    "beds",
    "Bathrooms",
    "house_size",
    "Lot Size Square Feet",
    "MLS Area",
    "Year Built",
    "HOA Fee",
    "Sewer",
    "Cooling",
    "Heating",
    "Parking Features"
]

df_selected = df[selected_cols]
df_selected.head(20)

,Latitude,Longitude,price,County,beds,Bathrooms,house_size,Lot Size Square Feet,MLS Area,Year Built,HOA Fee,Sewer,Cooling,Heating,Parking Features
0,47.253662,-122.501020,280000.0,Pierce,2,1.00,800.0,21000.0,26 - Central Tacoma,1950,0.0,Sewer Connected,None,Baseboard,Attached Garage
1,47.135711,-122.447555,530000.0,Pierce,3,2.50,1944.0,9951.0,69 - Parkland,2018,0.0,Sewer Connected,None,Forced Air,Attached Garage
2,47.091209,-122.381868,585950.0,Pierce,4,2.25,1916.0,6007.0,99 - Spanaway,2025,85.0,Sewer Connected,Heat Pump,Forced Air,Attached Garage
3,47.285087,-122.369776,530000.0,Pierce,3,2.50,1436.0,5750.0,94 - Browns Point,1989,0.0,Sewer Connected,None,Forced Air,Attached Garage
4,47.286240,-122.517141,475000.0,Pierce,3,1.00,951.0,6444.0,25 - North Tacoma,1982,0.0,Sewer Connected,None,Baseboard,Attached Garage
5,47.314928,-122.430700,1500000.0,Pierce,3,2.50,3580.0,35000.0,94 - Browns Point,1996,0.0,Septic Tank,Heat Pump,Forced Air,Attached Garage
6,47.208383,-122.412233,569900.0,Pierce,5,3.00,1810.0,2520.0,61 - Southeast Tacoma,2024,0.0,Sewer Connected,Central AC,Forced Air,Attached Garage
7,47.292824,-122.518687,925000.0,Pierce,5,2.25,2493.0,9240.0,13 - North Tacoma,1921,0.0,Sewer Connected,Ductless Mini Split,Wall Unit,Detached Garage
8,47.286981,-122.519019,634000.0,Pierce,4,1.75,1530.0,7550.0,25 - North Tacoma,1979,0.0,Sewer Connected,None,Forced Air,Attached Garage
9,47.291230,-122.390962,809250.0,Pierce,4,2.50,2396.0,9050.0,94 - Browns Point,1997,440.0,Sewer Connected,Forced Air,Forced Air,Attached Garage
10,47.176924,-122.381473,620000.0,Pierce,3,2.00,2074.0,20520.0,64 - Parkland/Midland,1961,0.0,Septic Tank,None,Other,Attached Garage
11,47.211306,-122.473432,346000.0,Pierce,2,1.00,728.0,6000.0,49 - South Tacoma,1942,0.0,Sewer Connected,None,Baseboard,Detached Garage
12,47.248404,-122.495429,480000.0,Pierce,3,1.25,1296.0,8125.0,26 - Central Tacoma,1922,0.0,Sewer Connected,Central AC,Forced Air,Detached Garage
13,47.179085,-122.411139,515900.0,Pierce,3,2.00,1157.0,4700.0,64 - Parkland/Midland,2024,70.0,Sewer Connected,Central AC,Forced Air,Attached Garage
14,47.131411,-122.411356,531000.0,Pierce,5,1.75,1796.0,15000.0,68 - Parkland,1960,0.0,Available,None,Forced Air,Detached Garage
15,47.203365,-122.412062,390000.0,Pierce,4,1.00,1008.0,6000.0,61 - Southeast Tacoma,1970,0.0,Sewer Connected,None,Baseboard,Attached Garage
16,47.266413,-122.454952,1095000.0,Pierce,6,2.75,3895.0,9620.0,20 - North Tacoma,1930,0.0,Sewer Connected,None,Other,Attached Garage
17,47.161867,-122.426826,415000.0,Pierce,3,1.75,1386.0,4205.0,64 - Parkland/Midland,1996,316.0,Sewer Connected,Central AC,Other,Attached Garage
18,47.263317,-122.510938,525678.0,Pierce,3,1.50,1446.0,8712.0,24 - North Tacoma,1960,0.0,Sewer Connected,None,Forced Air,Attached Garage
19,47.193653,-122.492637,325000.0,Pierce,2,0.75,1681.0,8712.0,45 - South Tacoma,1925,0.0,Sewer Connected,None,Wall Unit,Detached Garage

In [184]:
df[["Latitude",
    "Longitude",
    "price",
    "County",
    "beds",
    "Bathrooms",
    "house_size",
    "Lot Size Square Feet",
    "MLS Area",
    "Year Built",
    "HOA Fee",
    "Sewer",
    "Cooling",
    "Heating",
    "Parking Features"]].isnull().sum()

Latitude                0
Longitude               0
price                   0
County                  0
beds                    0
Bathrooms               0
house_size              0
Lot Size Square Feet    0
MLS Area                0
Year Built              0
HOA Fee                 0
Sewer                   0
Cooling                 0
Heating                 0
Parking Features        0
dtype: int64

Explanation: After completing the data cleaning process, 15 variables remained out of the original 20. These variables represent the most relevant and usable features for analysis, including numeric housing characteristics such as price, latitude, longitude, bedrooms, bathrooms, house size, lot size, year built, and HOA fee, as well as standardized categorical variables such as county, MLS area, heating type, cooling type, sewer type, and parking features. In addition, variables such as address, appliances, public remarks, and site features were removed because they contained unstructured text data, a large number of unique categories, and high levels of missing values (over 60%), making them unsuitable for clean encoding and numerical analysis. These steps ensured that the final dataset is suitable for statistical analysis.